version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: wallet-postgres
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - wallet-db-data:/var/lib/postgresql/data

  wallet-api:
    build: .
    container_name: wallet-api
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wallet
      SPRING_DATASOURCE_USERNAME: wallet
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_LIQUIBASE_ENABLED: true
    ports:
      - "8080:8080"

volumes:
  wallet-db-data:
