spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db_test
    username: wallet_user
    password: wallet_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: WARN
    com.wallet: INFO
